# Spring properties
spring:
  application:
    name: greeting-client-service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                       # Template location for this application onlyy
 
# Map the error path to error template (for Thymeleaf)
error: 
  path: /error
 
# Discovery Server Access
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${DOMAIN_PORT:${server.port}}
  
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:password@localhost:1111}/eureka/ 

security:
  user:
    password: ${eureka.password}
 
# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

greeting-service-url: ${GREETING_SERVICE_URL:http://GREETING-SERVICE}